image: maven:3-jdk-8

stages:
  - build
  - test
  - package

build:
  stage: build
  script: "mvn compile -B"
  
test:
  stage: test
  script: "mvn verify -B"
  
package:
  stage: package
  script: "mvn package -B"